CREATE TABLE PERSON ( 
 ID       INTEGER  NOT NULL AUTO_INCREMENT, 
 NAME     VARCHAR (20), 
 COUNTRY  VARCHAR (20), 
 PRIMARY KEY ( ID ) ) ; 
 
INSERT INTO PERSON ( ID, NAME, COUNTRY ) VALUES (4, 'aaaa', 'INDIA'); 
INSERT INTO PERSON ( ID, NAME, COUNTRY ) VALUES (1, 'aaaaa', 'a11'); 
INSERT INTO PERSON ( ID, NAME, COUNTRY ) VALUES (2, 'q', 'sss'); 
COMMIT;